### ISSUE TITLE
如下报错

### ISSUE THREAD

**Issue by Zheisbug** [asaotomo/FofaMap#21]
执行命令 
```
python3 fofamap.py -bq bb.txt
```
bb.txt内容为
```
domain="xxx"
domain="xxx"
domain="xxx"
.....
```
报错内容为
```Traceback (most recent call last):
  File "FofaMap-1.1.3/fofamap.py", line 646, in <module>
    bat_query(bat_query_file, scan_format)
  File "FofaMap-1.1.3/fofamap.py", line 401, in bat_query
    print_result(database, fields, scan_format)
  File "FofaMap-1.1.3/fofamap.py", line 377, in print_result
    table.add_row(item)
  File "/Library/Python/3.9/site-packages/prettytable/prettytable.py", line 1345, in add_row
    raise Exception(
Exception: Row has incorrect number of values, (actual) 8!=2 (expected)
```

**Comment by asaotomo** [comment]
可以提供bb.txt文件内的细节吗？我们测试了几个域名是没有问题的。
<img width="153" alt="image" src="https://github.com/asaotomo/FofaMap/assets/67818638/786b2a93-f61e-43db-bfea-c698d691d431">
<img width="1229" alt="image" src="https://github.com/asaotomo/FofaMap/assets/67818638/2418dbc6-40c0-4260-91cc-0fa9a454e14b">

**Comment by Zheisbug** [comment]
一些普通常见域名,大概放了几百个
不知道是不是因为api请求次数达到上限导致的,后来又正常了
