### ISSUE TITLE
Exception: Row has incorrect number of values, (actual) 8!=2 (expected)

### ISSUE THREAD

**Issue by UIWP0** [asaotomo/FofaMap#33]
![image](https://github.com/user-attachments/assets/19854c6b-8988-4d11-b3e9-966f680d4cc9)
运行命令：

python fofamap.py  -bq www2.txt  -o 123456.xlsx 

 _____      __       __  __     [*]联动 Nuclei
|  ___|__  / _| __ _|  \/  | __ _ _ __
| |_ / _ \| |_ / _` | |\/| |/ _` | '_ \
|  _| (_) |  _| (_| | |  | | (_| | |_) |
|_|  \___/|_|  \__,_|_|  |_|\__,_| .__/
                                 |_|   V1.1.3
#Coded By Hx0战队  Update:2024.02.06
======基础配置=======
[*]日志记录:关闭
[*]存活检测:开启
[*]搜索范围:一年内数据
[*]每页查询数量:10000条/页
======个人信息=======
[+] 邮箱：5****m
[+] 用户名：UIPW0
[+] F币剩余数量：0
[+] 是否是VIP：True
[+] VIP等级：2
======批量查询=======
[+] 任务文件：www2.txt
[+] 任务总数：1
[+] 当前任务：task-1
======查询内容=======
[+] 查询语句：ip="1.0.0.1"
[+] 查询参数：host,protocol,ip,port,title,domain,country_name
[+] 查询页数：1-5
======文档输出=======
[+] 文档输出成功！文件名为：fofa查询结果-任务1-【ip=_1.0.0.1_】-1723527094.xlsx
======查询结果=======
Traceback (most recent call last):
  File "fofamap.py", line 717, in <module>
    bat_query(bat_query_file, scan_format)
  File "fofamap.py", line 459, in bat_query
    print_result(database, fields, scan_format)
  File "fofamap.py", line 430, in print_result
    table.add_row(item)
  File "D:\Python\Python38\lib\site-packages\prettytable\prettytable.py", line 1345, in add_row
    raise Exception(
Exception: Row has incorrect number of values, (actual) 8!=2 (expected)

只有一行
![image](https://github.com/user-attachments/assets/d08a10b9-0e6f-45b9-b132-c6c3cb8eeb3b)

**Comment by asaotomo** [comment]
<img width="1504" alt="image" src="https://github.com/user-attachments/assets/7f1f8be2-d081-4164-9832-44d22f69f197">
我们经过测试，暂未发现问题，请您排查是否是fofa账号异常、配置文件错误或网络故障等因素导致的原因。
